---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 1.3.0
components:
  - name: OpenSearch
    repository: https://github.com/Korpics/OpenSearch.git
    ref: '1.3'
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: '1.3'
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: '1.3'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: '1.3'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: '1.3'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: '1.3'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: security
    repository: https://github.com/Korpics/security.git
    ref: "s390x"
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: tags/1.3.0.0
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: '1.3'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: '1.3'
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: plugin
  - name: dashboards-reports
    repository: https://github.com/opensearch-project/dashboards-reports.git
    ref: '1.3'
    working_directory: reports-scheduler
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability
    ref: '1.3'
    working_directory: opensearch-observability
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
